### PR TITLE
config: Add CMake supported application profiles variable

### PR DESCRIPTION
**Pull request by rajkan01**
Please enter the commit message for your changes. Lines starting

### Description
- Added the target config supported_application_profiles support
- Updated the existing test to validate supported_application_profiles target config
- Added the news file

### Test Coverage

- [ ]  This change is covered by existing or additional automated tests.
- [x]  Manual testing has been performed (and evidence provided) as automated testing was not feasible.
- [ ]  Additional tests are not required for this change (e.g. documentation update).

### CODE REVIEW

**Review by Patater — APPROVED** [review]
LGTM

**Comment by rajkan01** [comment]
I am not sure how CircleCI got invoked and failed with below error without config
```No .circleci/config.yml was found in your project. Click Add Config to choose how to add a config file or refer to documentation.```

**Comment by Patater** [comment]
CircleCI is being trialed in a branch. We can ignore errors with it for now, as it isn't being used on the master branch yet.

**Comment by jainvikas8** [comment]
Ok, to merge, but #98 needs to be addressed as a separate PR when other dependencies are resolved.

**Review by hugueskamba — APPROVED** [review]

**Pull request merged**
